# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Thermal Image Temperature Extraction
#' @description Extracts temperature data from an R-JPEG thermal image using DJI's Thermal SDK.
#' @param filepath_image Path to the R-JPEG thermal image file.
#' @param image_height Image height in pixels.
#' @param image_width Image width in pixels.
#' @param object_distance Distance to the target in meters (1-25m).
#' @param relative_humidity Relative humidity of the environment (20-100\%).
#' @param emissivity Emissivity of the target surface (0.10-1.00).
#' @param reflected_apparent_temperature Reflected apparent temperature in Celsius (-40.0 to 500.0 deg C).
#' @param filepath_dll Path to the dynamic link library (DLL) for processing.
#' @return A numeric matrix representing the temperature values of the image.
get_temp_dirp_cpp <- function(filepath_image, image_height, image_width, object_distance, relative_humidity, emissivity, reflected_apparent_temperature, filepath_dll) {
    .Call(`_theRmalUAV_get_temp_dirp_cpp`, filepath_image, image_height, image_width, object_distance, relative_humidity, emissivity, reflected_apparent_temperature, filepath_dll)
}

